name: push

on:
  push:
    branches:
      - 'dev'
      - '!staging'
      - 'feat/*'
    paths:
      - '**.ts'
      - 'test/**'
  pull_request:
    types:
      - opened
      - closed
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}