name: push

on: issue_comment

jobs:
  job1:
    runs-on: ubuntu-latest
    if: $ {{ github.event.issue.push }}

    steps:
      - name: Execute job 1
        run: echo job 1

  job2:
    runs-on: ubuntu-latest
    if: $ {{ github.event.issue.push }}

    steps:
      - name: Execute job 2
        run: echo job 2